name: parkir
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.4
  get: ^4.7.2
  hexcolor: ^3.0.1
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.9
  uuid: ^4.5.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.7
  url_launcher: ^6.3.1
  http: ^1.4.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true
  assets:
        - assets/images/
        - assets/images/logo_parkiryukk.png
        - assets/images/avatar.jpeg
  fonts:
      - family: Alike
        fonts:
          - asset: assets/fonts/Alike-Regular.ttf 